dependecies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
dotenv: .env
networks:
  goerli:
    priority_fee: null

wallets:
  from_key: ${PRIVATE_KEY}
